import type { Metadata } from "next";
import "./globals.css";
import PrelineScript from "../components/PrelineScript";


export const metadata: Metadata = {
  title: "Pay Ahiyoyo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="dark:bg-neutral-900">
      <main>{children}</main>
      </body>
      <PrelineScript />
    </html>
  );
}
